services:
  debuglife-backend:
    build:
      context: .
      dockerfile: ./compose/production/debuglife/backend/Dockerfile
    image: debuglife-backend
    command: /start
    volumes:
      - .:/opt/debuglife
    env_file:
      - ./.env/.prod
    ports:
      - "8001:8000"
    depends_on:
      - debuglife-db
      - debuglife-redis
    networks:
      - debuglife-network
  
  debuglife-frontend:
    build:
      context: .
      dockerfile: ./compose/production/debuglife/frontend/Dockerfile
    image: debuglife-frontend
    ports:
      - "3001:3000"
    depends_on:
      - debuglife-backend
    networks:
      - debuglife-network

  debuglife-db:
    image: postgres:14.4
    volumes:
      - debuglife_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env/.prod
    ports:
      - "5435:5432"
    networks:
      - debuglife-network

  debuglife-redis:
    image: redis:7.0.4
    networks:
      - debuglife-network

  debuglife-celery_worker_1:
    build:
      context: .
      dockerfile: ./compose/production/debuglife/backend/Dockerfile
    image: debuglife-celeryworker
    command: /start-celeryworker
    volumes:
      - .:/opt/debuglife
    env_file:
      - ./.env/.prod
    environment:
      - CELERY_QUEUE=initialise_ebay
    depends_on:
      - debuglife-db
      - debuglife-redis
    networks:
      - debuglife-network

  debuglife-celery_worker_2:
    build:
      context: .
      dockerfile: ./compose/production/debuglife/backend/Dockerfile
    image: debuglife-celeryworker
    command: /start-celeryworker
    volumes:
      - .:/opt/debuglife
    env_file:
      - ./.env/.prod
    environment:
      - CELERY_QUEUE=ebay
    depends_on:
      - debuglife-db
      - debuglife-redis
    networks:
      - debuglife-network

  debuglife-celery_worker_3:
    build:
      context: .
      dockerfile: ./compose/production/debuglife/backend/Dockerfile
    image: debuglife-celeryworker
    command: /start-celeryworker
    volumes:
      - .:/opt/debuglife
    env_file:
      - ./.env/.prod
    environment:
      - CELERY_QUEUE=email
    depends_on:
      - debuglife-db
      - debuglife-redis
    networks:
      - debuglife-network

  debuglife-celery_beat:
    build:
      context: .
      dockerfile: ./compose/production/debuglife/backend/Dockerfile
    image: debuglife-celerybeat
    command: /start-celerybeat
    volumes:
      - .:/opt/debuglife
    env_file:
      - ./.env/.prod
    depends_on:
      - debuglife-db
      - debuglife-redis
    networks:
      - debuglife-network

  debuglife-flower:
    build:
      context: .
      dockerfile: ./compose/production/debuglife/backend/Dockerfile
    image: debuglife-flower
    command: /start-flower
    volumes:
      - .:/opt/debuglife
    env_file:
      - ./.env/.prod
    ports:
      - "5559:5555"
    depends_on:
      - debuglife-db
      - debuglife-redis
    networks:
      - debuglife-network
  
  debuglife-nginx:
    build:
      context: .
      dockerfile: ./compose/production/debuglife/nginx/Dockerfile
    image: debuglife-nginx
    volumes:
      - .:/opt/debuglife
    ports:
      - "8085:80"
    depends_on:
      - debuglife-backend
      - debuglife-frontend
    networks:
      - debuglife-network

networks:
  debuglife-network:
    driver: bridge

volumes:
  debuglife_postgres_data: